# Generated by Django 2.2.17 on 2021-01-07 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assign', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assign.ProjectPhase'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(through='assign.ProjectMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyworkingtime',
            name='project_member',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='assign.ProjectMember'),
        ),
        migrations.AddField(
            model_name='dailyworkingtime',
            name='project_member',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='assign.ProjectMember'),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='project_member_unique'),
        ),
    ]
