# Generated by Django 2.2.17 on 2021-01-05 22:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0003_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default='1', on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
