# Generated by Django 2.2.17 on 2021-01-05 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assign', '0005_auto_20210105_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_day', models.CharField(max_length=10)),
                ('target_month', models.CharField(max_length=10)),
                ('working_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyWorkingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_month', models.CharField(max_length=10)),
                ('planed_working_time', models.IntegerField()),
                ('actual_working_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.CharField(max_length=10)),
                ('end_date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_management', models.BooleanField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assign.ProjectPhase'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(through='assign.ProjectMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
