# Generated by Django 2.2.17 on 2021-01-06 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0007_auto_20210105_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworkingtime',
            name='project_member',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='assign.ProjectMember'),
        ),
        migrations.AddField(
            model_name='monthlyworkingtime',
            name='project_member',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='assign.ProjectMember'),
        ),
    ]
