# Generated by Django 2.2.17 on 2021-01-06 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0008_auto_20210106_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='is_management',
        ),
    ]
