# Generated by Django 2.2.17 on 2021-01-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0009_remove_projectmember_is_management'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='project_member_unique'),
        ),
    ]
