# Generated by Django 2.2.17 on 2021-01-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.IntegerField(null=True, verbose_name='role id'),
        ),
        migrations.AddField(
            model_name='user',
            name='unit_price',
            field=models.IntegerField(null=True, verbose_name='unit price'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='full name'),
        ),
    ]
