# Generated by Django 2.2.17 on 2021-01-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210105_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.ForeignKey(help_text='Specific Roles for this user.', null=True, on_delete=False, related_name='user_set', related_query_name='user', to='users.Role', verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unit_price',
            field=models.IntegerField(null=True, verbose_name='unit price(万円/月)'),
        ),
    ]
