# Generated by Django 2.2.17 on 2021-01-05 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210105_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(help_text='Specific Roles for this user.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_set', related_query_name='user', to='users.Role', verbose_name='role'),
        ),
    ]
