# Generated by Django 2.2.17 on 2021-01-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210105_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_management',
            field=models.BooleanField(default=False),
        ),
    ]
